<a href="https://colab.research.google.com/github/dflorness21/Linear_Algebra_Coding_Projects/blob/master/Exam_2_Takehome_Portion.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the numpy library...

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

Page 4

In [4]:
M = np.matrix([[5, 1, 11],
               [1, 11, 1],
               [11, 1, 35]])

M

matrix([[ 5,  1, 11],
        [ 1, 11,  1],
        [11,  1, 35]])

In [5]:
np.linalg.inv(M)

matrix([[ 0.66666667, -0.04166667, -0.20833333],
        [-0.04166667,  0.09375   ,  0.01041667],
        [-0.20833333,  0.01041667,  0.09375   ]])

Page 5

In [16]:
r1 = [2, -4, 4, 0]
r2 = [2, -2, 6, 0]
r3 = [-4, -1, 1, 0]

In [17]:
print(r1)

n1 = r1
print(n1)

print(np.sqrt(np.dot(n1, n1)))

u1 = n1 / np.sqrt(np.dot(n1, n1))
print(u1)

[2, -4, 4, 0]
[2, -4, 4, 0]
6.0
[ 0.33333333 -0.66666667  0.66666667  0.        ]


In [18]:
np.dot(u1, u1)

1.0

In [19]:
print(r2)

n2 = r2 - np.dot(r2, u1) * u1
print(n2)

print(np.sqrt(np.dot(n2, n2)))

u2 = n2 / np.sqrt(np.dot(n2, n2))
print(u2)

[2, -2, 6, 0]
[0. 2. 2. 0.]
2.8284271247461903
[0.         0.70710678 0.70710678 0.        ]


In [20]:
np.dot(u2, u2)

0.9999999999999998

In [21]:
print(r3)

n3 = r3 - np.dot(r3, u1) * u1 - np.dot(r3, u2) * u2
print(n3)

print(np.sqrt(np.dot(n3, n3)))

u3 = n3 / np.sqrt(np.dot(n3, n3))
print(u3)

[-4, -1, 1, 0]
[-4. -1.  1.  0.]
4.242640687119285
[-0.94280904 -0.23570226  0.23570226  0.        ]


In [23]:
u4 = [0, 0, 0, 1]
p = [3, -2, 6, -5]

print(np.dot(u1, p))
print(np.dot(u2, p))
print(np.dot(u3, p))
print(np.dot(u4, p))

6.333333333333333
2.82842712474619
-0.9428090415820634
-5


Page 6

In [24]:
M = np.matrix([[2, 4, 8, 0.5],
               [2, -0.5, 2, -0.25],
               [0, 4, -2, 0],
               [4, 0, 2, 1]])

np.linalg.det(M)

108.00000000000003