<a href="https://colab.research.google.com/github/dflorness21/Linear_Algebra_Coding_Projects/blob/master/EXAM_1_TAKEHOME_PORTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
from numpy import c_

ll = "loaded"

Transition Matrices and Markov Chains
  A drug administered to a patient is measured in four different organs every 10 minutes. Measurements in organs A, B, C, and D indicate:

Measurements
*   30% of the drug in A moves to B
*   30% of the drug in A moves to C
*   20% of the drug in B moves to A
*   40% of the drug in B moves to C
*   50% of the drug in C moves to A
*   50% of the drug in C moves to D

Any drug not moving from one state to another remains in the original state.

(a) Give the transition matrix.

In [3]:
M = np.matrix([[.4, .2, .5, 0],
               [.3, .4, 0, 0],
               [.3, .4, 0, 0],
               [0, 0, .5, 1]])
M

matrix([[0.4, 0.2, 0.5, 0. ],
        [0.3, 0.4, 0. , 0. ],
        [0.3, 0.4, 0. , 0. ],
        [0. , 0. , 0.5, 1. ]])

(b) At time t = 0min, measurements indicate 100mg of the drug are in state A and 200mg of the drug are in state B. Determine the amount of drug in each state when t = 10min and t = 20min.

In [4]:
x0 = np.matrix([[100], [200], [0], [0]])
x0

matrix([[100],
        [200],
        [  0],
        [  0]])

In [9]:
M * x0

matrix([[ 80.],
        [110.],
        [110.],
        [  0.]])

In [10]:
M ** 2 * x0

matrix([[109.],
        [ 68.],
        [ 68.],
        [ 55.]])

(c) Determine how much of the total substances is in each state after 4 hours.

In [11]:
M ** 24 * x0

matrix([[  3.68702513],
        [  2.41372454],
        [  2.41372454],
        [291.48552579]])