<a href="https://colab.research.google.com/github/dflorness21/Linear_Algebra_Coding_Projects/blob/master/hw_wk10_02_determinants.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import the numpy library...

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [21]:
# create the matrix:
A = np.matrix([[10, 7],
               [8, 9]])

B = np.matrix([[-10, -1],
               [-4, 7]])

C = np.matrix([[1, -3],
               [7, 7]])

D = A*B
E = B*A
F = A*C
G = C*A
H = B*C
I = C*B
J = A*B*C
K = A*C*B
L = C*B*A

print(D)
print(E)
print(F)
print(G)
print(H)
print(I)
print(J)
print(K)
print(L)

[[-128   39]
 [-116   55]]
[[-108  -79]
 [  16   35]]
[[59 19]
 [71 39]]
[[-14 -20]
 [126 112]]
[[-17  23]
 [ 45  61]]
[[  2 -22]
 [-98  42]]
[[145 657]
 [269 733]]
[[-666   74]
 [-866  202]]
[[-156 -184]
 [-644 -308]]


In [22]:
print(np.linalg.det(D))
print(np.linalg.det(E))
print(np.linalg.det(F))
print(np.linalg.det(G))
print(np.linalg.det(H))
print(np.linalg.det(I))
print(np.linalg.det(J))
print(np.linalg.det(K))
print(np.linalg.det(L))

-2515.999999999999
-2516.0000000000014
951.9999999999997
951.9999999999997
-2071.9999999999995
-2071.9999999999995
-70447.99999999994
-70447.99999999994
-70447.99999999994


In [27]:
# create the matrix:
A = np.matrix([[3, 2, 3],
               [-6, 1, -10],
               [-8, -9, -9]])

B = np.matrix([[1, -2, 1],
               [5, 5, 4],
               [4, 0, 0]])

C = np.matrix([[1, 0, 0],
               [0, 2, 0],
               [-3, -2, 1]])

D = A*B
E = B*A
F = A*C
G = C*A
H = B*C
I = C*B
J = A*B*C
K = A*C*B
L = C*B*A

print(D)
print(E)
print(F)
print(G)
print(H)
print(I)
print(J)
print(K)
print(L)

[[ 25   4  11]
 [-41  17  -2]
 [-89 -29 -44]]
[[  7  -9  14]
 [-47 -21 -71]
 [ 12   8  12]]
[[ -6  -2   3]
 [ 24  22 -10]
 [ 19   0  -9]]
[[  3   2   3]
 [-12   2 -20]
 [ -5 -17   2]]
[[-2 -6  1]
 [-7  2  4]
 [ 4  0  0]]
[[  1  -2   1]
 [ 10  10   8]
 [ -9  -4 -11]]
[[ -8 -14  11]
 [-35  38  -2]
 [ 43  30 -44]]
[[ -4   2 -14]
 [ 94  62 112]
 [-17 -38  19]]
[[   7   -9   14]
 [ -94  -42 -142]
 [  85   77  112]]


In [28]:
print(np.linalg.det(D))
print(np.linalg.det(E))
print(np.linalg.det(F))
print(np.linalg.det(G))
print(np.linalg.det(H))
print(np.linalg.det(I))
print(np.linalg.det(J))
print(np.linalg.det(K))
print(np.linalg.det(L))

3067.9999999999973
3067.9999999999973
-118.00000000000004
-118.00000000000004
-103.99999999999999
-104.00000000000007
6135.999999999995
6136.000000000006
6136.000000000006


In [30]:
P = np.matrix([[2, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

Q = np.matrix([[-1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

R = np.matrix([[3, 0, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
               [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

Z = P*Q*R*Q*P

np.linalg.det(Z)

12.0