<a href="https://colab.research.google.com/github/dflorness21/Linear_Algebra_Coding_Projects/blob/master/Practice_with_Gram_Schmidt_Process.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
# Import the numpy library...

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [32]:
# How do I do a dot product?

print(np.dot([1, 2], [3, 4]))

# How do I find the magnitude in np?

print(np.sqrt(np.dot([1, 2], [1, 2])))

11
2.23606797749979


In [34]:
# Define the original vectors:

r1 = [2, 4, 0, 0]
r2 = [1, 2, 3, 6]
r3 = [2, -1, 2, -1]
r4 = [1, 2, 3, 4]

print(r1)
print(r2)
print(r3)
print(r4)

[2, 4, 0, 0]
[1, 2, 3, 6]
[2, -1, 2, -1]
[1, 2, 3, 4]


In [35]:
# Find the first nice basis vector u1

# 1: Pick a new vector

print(r1)

# 2: Subtract the basis of r1 onto the nice basis u1, u2, u3, ...
# and save as a temp vector n1

n1 = r1
print(n1)

# 3: Find the magnitude of n1

print(np.sqrt(np.dot(n1, n1)))

# 4: Create the nice basis vector u1 = 1 / | n1 | * n1

u1 = n1 / np.sqrt(np.dot(n1, n1))
print(u1)

[2, 4, 0, 0]
[2, 4, 0, 0]
4.47213595499958
[0.4472136  0.89442719 0.         0.        ]


In [36]:
# Check that u1 has magnitude 1:

np.dot(u1, u1)

0.9999999999999999

In [37]:
# Find the second nice basis vector u1

# 1: Pick a new vector

print(r2)

# 2: Subtract the basis of r2 onto the nice basis u1, u2, u3, ...
# and save as a temp vector n2

n2 = r2 - np.dot(r2, u1) * u1
print(n2)

# 3: Find the magnitude of n2

print(np.sqrt(np.dot(n2, n2)))

# 4: Create the nice basis vector u2 = 1 / | n2 | * n2

u2 = n2 / np.sqrt(np.dot(n2, n2))
print(u2)

[1, 2, 3, 6]
[0. 0. 3. 6.]
6.708203932499369
[0.         0.         0.4472136  0.89442719]


In [38]:
# Check that u1 and u2 are orthogonal:

print(np.dot(u1, u2))

# Check that u2 has magnitude 1:

print(np.dot(u2, u2))

0.0
0.9999999999999999


In [39]:
# Find the third nice basis vector u1

# 1: Pick a new vector

print(r3)

# 2: Subtract the basis of r3 onto the nice basis u1, u2, u3, ...
# and save as a temp vector n3

n3 = r3 - np.dot(r3, u1) * u1 - np.dot(r3, u2) * u2
print(n3)

# 3: Find the magnitude of n3

print(np.sqrt(np.dot(n3, n3)))

# 4: Create the nice basis vector u3 = 1 / | n3 | * n3

u3 = n3 / np.sqrt(np.dot(n3, n3))
print(u3)

[2, -1, 2, -1]
[ 2. -1.  2. -1.]
3.1622776601683795
[ 0.63245553 -0.31622777  0.63245553 -0.31622777]


In [42]:
# Check that u3 is orthogonal to u1 and u2

print(np.dot(u1, u3))
print(np.dot(u2, u3))

# Check that u3 has magnitude 1

print(np.dot(u3, u3))

0.0
0.0
1.0


In [43]:
# Find the fourth nice basis vector u1

# 1: Pick a new vector

print(r4)

# 2: Subtract the basis of r4 onto the nice basis u1, u2, u3, ...
# and save as a temp vector n4

n4 = r4 - np.dot(r4, u1) * u1 - np.dot(r4, u2) * u2 - np.dot(r4, u3) * u3
print(n4)

# 3: Find the magnitude of n4

print(np.sqrt(np.dot(n4, n4)))

# 4: Create the nice basis vector u4 = 1 / | n4 | * n4

u4 = n4 / np.sqrt(np.dot(n4, n4))
print(u4)

[1, 2, 3, 4]
[-0.4  0.2  0.4 -0.2]
0.6324555320336759
[-0.63245553  0.31622777  0.63245553 -0.31622777]


In [44]:
# Check that u4 is orthogonal to u1, u2, and u3

print(np.dot(u1, u4))
print(np.dot(u2, u4))
print(np.dot(u3, u4))

# Check that u4 has magnitude 1

print(np.dot(u4, u4))

0.0
9.43689570931383e-16
9.71445146547012e-17
0.9999999999999998


Homework: Gram-Schmidt Orthonormalization Process - Part 2

In [48]:
# Define the original vectors:

r1 = [3, 0, 3, 0]
r2 = [3, 2, 3, 3]
r3 = [-7, -4, -5, -6]
r4 = [-7, -3, -11, 2]

print(r1)
print(r2)
print(r3)
print(r4)

[3, 0, 3, 0]
[3, 2, 3, 3]
[-7, -4, -5, -6]
[-7, -3, -11, 2]


In [49]:
# Find the first nice basis vector u1

# 1: Pick a new vector

print(r1)

# 2: Subtract the basis of r1 onto the nice basis u1, u2, u3, ...
# and save as a temp vector n1

n1 = r1
print(n1)

# 3: Find the magnitude of n1

print(np.sqrt(np.dot(n1, n1)))

# 4: Create the nice basis vector u1 = 1 / | n1 | * n1

u1 = n1 / np.sqrt(np.dot(n1, n1))
print(u1)

[3, 0, 3, 0]
[3, 0, 3, 0]
4.242640687119285
[0.70710678 0.         0.70710678 0.        ]


In [50]:
# Find the second nice basis vector u1

# 1: Pick a new vector

print(r2)

# 2: Subtract the basis of r2 onto the nice basis u1, u2, u3, ...
# and save as a temp vector n2

n2 = r2 - np.dot(r2, u1) * u1
print(n2)

# 3: Find the magnitude of n2

print(np.sqrt(np.dot(n2, n2)))

# 4: Create the nice basis vector u2 = 1 / | n2 | * n2

u2 = n2 / np.sqrt(np.dot(n2, n2))
print(u2)

[3, 2, 3, 3]
[-4.4408921e-16  2.0000000e+00 -4.4408921e-16  3.0000000e+00]
3.605551275463989
[-1.23168186e-16  5.54700196e-01 -1.23168186e-16  8.32050294e-01]


In [51]:
# Find the third nice basis vector u1

# 1: Pick a new vector

print(r3)

# 2: Subtract the basis of r3 onto the nice basis u1, u2, u3, ...
# and save as a temp vector n3

n3 = r3 - np.dot(r3, u1) * u1 - np.dot(r3, u2) * u2
print(n3)

# 3: Find the magnitude of n3

print(np.sqrt(np.dot(n3, n3)))

# 4: Create the nice basis vector u3 = 1 / | n3 | * n3

u3 = n3 / np.sqrt(np.dot(n3, n3))
print(u3)

[-7, -4, -5, -6]
[-1.0000000e+00 -4.4408921e-16  1.0000000e+00 -8.8817842e-16]
1.4142135623730951
[-7.07106781e-01 -3.14018492e-16  7.07106781e-01 -6.28036983e-16]


In [52]:
# Find the fourth nice basis vector u1

# 1: Pick a new vector

print(r4)

# 2: Subtract the basis of r4 onto the nice basis u1, u2, u3, ...
# and save as a temp vector n4

n4 = r4 - np.dot(r4, u1) * u1 - np.dot(r4, u2) * u2 - np.dot(r4, u3) * u3
print(n4)

# 3: Find the magnitude of n4

print(np.sqrt(np.dot(n4, n4)))

# 4: Create the nice basis vector u4 = 1 / | n4 | * n4

u4 = n4 / np.sqrt(np.dot(n4, n4))
print(u4)

[-7, -3, -11, 2]
[ 0. -3.  0.  2.]
3.605551275463989
[ 0.         -0.83205029  0.          0.5547002 ]


In [53]:
print(np.dot(u1, u2))
print(np.dot(u1, u3))
print(np.dot(u1, u4))
print(np.dot(u2, u3))
print(np.dot(u2, u4))
print(np.dot(u3, u4))

-1.741861189847285e-16
0.0
0.0
-6.967444759389139e-16
-1.2212453270876722e-15
-8.709305949236341e-17


In [54]:
print(np.dot(u1, u1))
print(np.dot(u2, u2))
print(np.dot(u3, u3))
print(np.dot(u4, u4))

1.0000000000000002
1.0
0.9999999999999998
1.0
